
package ejemplo;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 * esto 
 * @author Nausicaa
 */
public class Formulario1 extends javax.swing.JFrame {

    /**
     * Creates new form Formulario por que
     */
    public Formulario1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Button_Nitro = new javax.swing.JButton();
        Button_Facebook = new javax.swing.JButton();
        Button_Exit = new javax.swing.JButton();
        Button_Team = new javax.swing.JButton();
        Button_Gmail = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Button_Nitro.setText("Nitro");
        Button_Nitro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_NitroActionPerformed(evt);
            }
        });

        Button_Facebook.setText("Facebook");
        Button_Facebook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_FacebookActionPerformed(evt);
            }
        });

        Button_Exit.setText("Exit");
        Button_Exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Button_ExitMouseClicked(evt);
            }
        });

        Button_Team.setText("Team Viewer");
        Button_Team.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_TeamActionPerformed(evt);
            }
        });

        Button_Gmail.setText("Gmail");
        Button_Gmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_GmailActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(141, 141, 141)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Button_Exit)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Button_Facebook)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Button_Gmail))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Button_Nitro)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                                .addComponent(Button_Team)))
                        .addGap(51, 51, 51))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Button_Nitro)
                    .addComponent(Button_Team))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Button_Facebook)
                    .addComponent(Button_Gmail))
                .addGap(50, 50, 50)
                .addComponent(Button_Exit)
                .addContainerGap(79, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public static void ejecutar (int opcion){
        Runtime app = Runtime.getRuntime();
        try {
            switch (opcion){
                case 1: 
                    app.exec("C:\\Program Files\\Nitro\\Pro 10\\NitroPDF.exe");
                    break;
                case 2:
                    app.exec("C:\\Program Files (x86)\\TeamViewer\\TeamViewer.exe");
                    break;
                case 3:
                    app.exec("C:/Windows/System32/cmd.exe /K start https://www.facebook.com/");
                    break;
                case 4:
                    app.exec("C:/Windows/System32/cmd.exe /K start https://mail.google.com/mail/u/0/?tab=rm&ogbl#inbox");
                    break;
            }
            
            
        } catch (IOException ex) {
            Logger.getLogger(Formulario1.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null,"Error abrir app "+ ex.getMessage().toString());
        }
    }
     /**
     * vamos a ejecutar los botones
     */
    private void Button_ExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Button_ExitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_Button_ExitMouseClicked

    private void Button_NitroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_NitroActionPerformed
        ejecutar(1);
    }//GEN-LAST:event_Button_NitroActionPerformed

    private void Button_TeamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_TeamActionPerformed
        ejecutar (2);
    }//GEN-LAST:event_Button_TeamActionPerformed

    private void Button_FacebookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_FacebookActionPerformed
       ejecutar (3);
    }//GEN-LAST:event_Button_FacebookActionPerformed

    private void Button_GmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_GmailActionPerformed
        ejecutar (4);
    }//GEN-LAST:event_Button_GmailActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Formulario1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Formulario1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Formulario1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Formulario1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Formulario1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_Exit;
    private javax.swing.JButton Button_Facebook;
    private javax.swing.JButton Button_Gmail;
    private javax.swing.JButton Button_Nitro;
    private javax.swing.JButton Button_Team;
    // End of variables declaration//GEN-END:variables
}
